name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies Backend
        run: npm install
      - name: Install Dependencies Frontend
        run: cd bloglist-frontend && npm install

      - name: Check Code Style
        run: npm run eslint

      - name: Start Backened in Test Mode
        run: npm run start:test
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NODE_ENV: test
      - name: Start Frontend
        run: cd bloglist-frontend && npm run dev

      - name: Run Backend Tests
        run: npm run test
      - name: Run Frontend Tests
        run: cd bloglist-frontend/tests-frontend && npm run test